config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  
  resources :users
  resource :session
  
  namespace :api, defaults: { format: :json } do
    resources :listings
  end 
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates :title, :user_id, presence: true
  belongs_to :user
  geocoded_by :address

  after_validation :geocode #, if: address_changed?
  
  def is_member?(user)
    return true if user.id == self.user_id
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_token
  
  has_many :listings
  
  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return @user if (@user && @user.is_password?(password))
    nil
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def password=(password) 
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token 
  end
  
  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
    
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    before_action :require_signed_in!
  end
end
    

app/controllers/api/listings_controller.rb
module Api
  class ListingsController < ApiController
    
    def create
      @listing = current_user.listings.new(listing_params)
      
      if @listing.save
        render json: @listing
      else
       render json: @listing.errors.full_messages, 
              status: :unprocessable_entity
      end
    end
    
    def index
      @listings = Listing.all
      render :index
    end
    
    def show
      @listing = Listing.find(params[:id])
    end
    
    def destroy
      @listing = current_user.listings.find(params[:id])
      @listing.try(:destroy)
      render json: {}
    end
    
    private
    
    def listing_params
      params.require(:listing).permit(:title)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?

  def current_user
    return nil if session[:session_token].nil?
    current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def login(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def logout
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_signed_in!
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    
    if @user
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!
  
  def root 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login(@user)
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new # probably not right
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/#{gravatar_id}.png"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Science Fair BnB</title>
  <link rel="shortcut icon" href="assets/favicon.ico" />
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <div class="navbar-brand" style="position:relative;top:-15px">
          <a href="#">
         <img src="/assets/logo.png" 
              style="height:50px;width:250px" 
              class="orange-hover-border img-rounded"> 
         </a>
      </div>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        
        <% if current_user %> 
        
          <li class="active"><%= link_to "Log out", session_url, 
                    method: :delete, class: "active customized"%><span   
                    class="sr-only">(current)</span></li>
                    
          <li class="active">
            <a class="active customized" href="#">Edit Profile</a>
          </li>
          
        <% else %>
        
         <li class="active"><a class="customized" data-toggle="modal"      
             href="#guestSignInModal">Guest Log In</a>
             <span class="sr-only"></span></li>
        
        <li class="active"><a data-toggle="modal" 
            class="customized" href="#signInModal">Log In</a>
            <span class="sr-only"></span></li>
        
         <li class="active"><a data-toggle="modal" 
             class="customized" href="#signUpModal">Sign Up</a>
             <span class="sr-only"></span></li>
         
        <% end %>
        
        </ul>
      </div>
    </div>
  </nav>


  <%= yield %>


</body>
</html>

app/views/static_pages/root.html.erb
<div id="main"><div>
<h3>root</h3>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-xs-4 col-xs-offset-4'>
    <h3>Sign Up</h3>
    <form action="/users"  method="POST" role="form">
      <div class='form-group'>
        <input type='hidden'
               name='authenticity_token'
               value="<%= form_authenticity_token %>">
               
        <label for='user_email'>E-mail</label>
        <input type='email'
               id='user_email'
               class='form-control'
               placeholder='E-mail'
               name='user[email]'>
               
        <label for='user_password'>Password</label>
        <input type='password'
               id='user_password'
               class='form-control'
               placeholder='password'
               name='user[password]'><br>
        
        <button class='form-control btn btn-primary'>Sign Up</button>
        <div>
    </form>
  <div>
</div>